version: '3.8'

services:
  gym-app:
    build: .
    container_name: gym-app
    expose:
      - "5173"
    depends_on:
      - nginx

  nginx:
    image: nginx:latest
    container_name: nginx-3
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf