version: '3.8'

services:
  workout-app:
    build: .
    container_name: workout-app
    expose:
      - "3000"
    depends_on:
      - nginx

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf